### ISSUE TITLE
webUI一片空白

### ISSUE THREAD

**Issue by Unihis** [Gaojianli/pbh-fe#127]
打开webUI是空白页，是否有可能是这项报错导致的

[16:48:54] [/ERROR]: Unable to complete scheduled tasks
java.util.concurrent.CompletionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
	at java.net.http/jdk.internal.net.http.Exchange.checkCancelled(Exchange.java:330) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.Exchange.cancel(Exchange.java:293) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.MultiExchange.cancel(MultiExchange.java:265) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectTimerEvent.handle(PlainHttpConnection.java:103) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1778) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1376) ~[java.net.http:?]
	Suppressed: java.lang.RuntimeException: java.util.concurrent.CompletionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
		at com.ghostchu.peerbanhelper.module.impl.rule.IPBlackRuleList.lambda$updateRule$10(IPBlackRuleList.java:222) ~[PeerBanHelper.jar:6.0.0]
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:914) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
		at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314) ~[?:?]
		at java.base/java.lang.VirtualThread.run(VirtualThread.java:309) ~[?:?]
	Caused by: java.util.concurrent.CompletionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
		at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
		at java.net.http/jdk.internal.net.http.Exchange.checkCancelled(Exchange.java:330) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.Exchange.cancel(Exchange.java:293) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.MultiExchange.cancel(MultiExchange.java:265) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectTimerEvent.handle(PlainHttpConnection.java:103) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1778) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1376) ~[java.net.http:?]
	Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
		at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:585) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:532) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:452) ~[java.net.http:?]
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
		at java.net.http/jdk.internal.net.http.Exchange.checkCancelled(Exchange.java:330) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.Exchange.cancel(Exchange.java:293) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.MultiExchange.cancel(MultiExchange.java:265) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectTimerEvent.handle(PlainHttpConnection.java:103) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1778) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1376) ~[java.net.http:?]
	Caused by: java.net.ConnectException: HTTP connect timed out
		at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:586) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:532) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:452) ~[java.net.http:?]
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
		at java.net.http/jdk.internal.net.http.Exchange.checkCancelled(Exchange.java:330) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.Exchange.cancel(Exchange.java:293) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.MultiExchange.cancel(MultiExchange.java:265) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectTimerEvent.handle(PlainHttpConnection.java:103) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1778) ~[java.net.http:?]
		at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1376) ~[java.net.http:?]
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:585) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:532) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:452) ~[java.net.http:?]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
	... 8 more
Caused by: java.net.ConnectException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:586) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:532) ~[java.net.http:?]
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:452) ~[java.net.http:?]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
	... 8 more

**Comment by Unihis** [comment]
更新为6.0版本后

**Comment by Ghost-chu** [comment]
请清除浏览器缓存&nbsp;


Ghost_chu
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年8月18日(星期天) 下午4:52
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: Re: [PBH-BTN/pbh-fe] webUI一片空白 (Issue #127)














 
更新为6.0版本后

**Comment by Unihis** [comment]
ok,恢复了
